name: test
description: A test app for harpo!
version: 1.0.0
homepage: https://github.com/iamtheblackunicorn/Harpo
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  harpo:
    git: git://github.com/iamtheblackunicorn/Harpo.git
